version: 0.2

phases:
  install:
    commands:
      # Use Node.js LTS
      - echo Installing dependencies...
      - npm install
  # pre_build:
  #   commands:
  #     - echo Running unit tests...
  #     - npm test
  build:
    commands:
      # Create the 'build' folder containing static files
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build 
  discard-paths: yes